// Generated by Dolphin transpiler
#include "dolphin_runtime.hpp"

int main() {
    dolphin_init();
    dolphin_print(var("Starting Access Point 'Dolphin-ESP'..."));
    var ip = DolphinWifi["softAP"](std::vector<var>{var("Dolphin-ESP"), var("12345678")});
    dolphin_print((var("Access Point started! Connect to 'Dolphin-ESP' WiFi and visit http://") + ip));
    pin led = pin(std::vector<var>{var(2), DOLPHIN_OUTPUT});

    led["write"](std::vector<var>{DOLPHIN_HIGH});
    var server = HTTP.Server();
    server.get(var("/"), var([=](const std::vector<var>& __args__) mutable -> var {
    var req = __args__.size() > 0 ? __args__[0] : var();
    var res = __args__.size() > 1 ? __args__[1] : var();
    res["html"](std::vector<var>{var("<html>\n<head>\n    <title>Dolphin LED Control</title>\n    <meta name='viewport' content='width=device-width, initial-scale=1'>\n    <style>\n        body {\n            font-family: sans-serif;\n            text-align: center;\n            margin-top: 50px;\n            background: #1e1e2e;\n            color: #cdd6f4;\n        }\n        h1 {\n            color: #f5c2e7;\n        }\n        .btn {\n            display: inline-block;\n            padding: 15px 30px;\n            font-size: 18px;\n            margin: 20px;\n            border: none;\n            border-radius: 8px;\n            cursor: pointer;\n            text-decoration: none;\n            font-weight: bold;\n        }\n        .btn-on {\n            background: #a6e3a1;\n            color: #11111b;\n        }\n        .btn-off {\n            background: #f38ba8;\n            color: #11111b;\n        }\n    </style>\n</head>\n<body>\n    <h1>Dolphin IoT LED Server</h1>\n    <p>Control the onboard LED of your ESP8266 board:</p>\n    <a href='/on' class='btn btn-on'>TURN LED ON</a>\n    <a href='/off' class='btn btn-off'>TURN LED OFF</a>\n</body>\n</html>")});    return var();
}));
    server.get(var("/on"), var([=](const std::vector<var>& __args__) mutable -> var {
    var req = __args__.size() > 0 ? __args__[0] : var();
    var res = __args__.size() > 1 ? __args__[1] : var();
    dolphin_print(var("Web request: Turn LED ON"));    led["write"](std::vector<var>{DOLPHIN_LOW});    res["html"](std::vector<var>{var("<html><head><meta http-equiv='refresh' content='0;url=/'></head></html>")});    return var();
}));
    server.get(var("/off"), var([=](const std::vector<var>& __args__) mutable -> var {
    var req = __args__.size() > 0 ? __args__[0] : var();
    var res = __args__.size() > 1 ? __args__[1] : var();
    dolphin_print(var("Web request: Turn LED OFF"));    led["write"](std::vector<var>{DOLPHIN_HIGH});    res["html"](std::vector<var>{var("<html><head><meta http-equiv='refresh' content='0;url=/'></head></html>")});    return var();
}));
    server.listen(var(80));
    dolphin_print(var("HTTP Server listening on port 80..."));
    while (true) {
{
            sleep(std::vector<var>{var(100)});        }
}
    return 0;
}
